### ISSUE TITLE
Spectral Python _ Hypercube not Responding

### ISSUE THREAD

**Issue by FarFromBoston** [spectralpython/spectral#90]
Im using the spectral python documentation to learn it:
http://www.spectralpython.net/graphics.html

Im up to showing the hypercube but cant figure out whats wrong. I can import everything just fine - I have wxpython and PyOpenGL installed correctly with conda

When i run cell '24' I get the hypercube window as "hypercube not responding"
then when i close it i get "Kernal died"
I have to then restart Jupyter...

Why cant I see the hypercube? im following the documentation page exactly.

![22222222222222](https://user-images.githubusercontent.com/25518651/59985423-eabae380-9674-11e9-8f07-11c8fd0aa929.jpg)

**Comment by tboggs** [comment]
I'm not sure if that will work from Jupyter due to the way the OpenGL window needs to run in a separate thread. Try running the same commands from the command line (outside of Jupyter) and see if it works for you there. If it doesn't work there, then you may just have a configuration issue. If it does work, then there is probably an incompatibility between the Jupyter kernel and python threading.

**Comment by FarFromBoston** [comment]
Using the windows powershell in the folder i tried to import wx and tried to run
view_cube(img, bands=[29, 19, 9])

Both came back with:

import wx
  File "C:\Users\lewis\Anaconda3\Lib\site-packages\wx\__init__.py", line 12, in <module>
    __version__ = wx.__version__.VERSION_STRING
AttributeError: 'module' object has no attribute '__version__'


my 'wx' package is bugged :/

**Comment by zspatter** [comment]
I'm having similar trouble with `view_cube()` function. I've been trying to follow the tutorial in the spectral documentation with scripts instead of Jupyter; however, I don't believe that is the intended usage. If I understand the documentation correctly, it is expected to be used with IPython.

As for displaying the hypercube - the note at the bottom of the [Hypercube Display section](http://www.spectralpython.net/graphics.html#hypercube-display) seems to have addressed this for me.

**Comment by tboggs** [comment]
@zspatter, yes the `view_cube` function is intended for interactive use so it should be used from the IPython command line.

**Comment by FarFromBoston** [comment]
@zspatter 

Yeh I saw the bottom section, but the problem i have is not a blank canvas its that it is "not responding"

**Comment by FarFromBoston** [comment]
yeh only jupyter is supposed to work,

i also tried using a cfommand prompt and setting it with
ipython --pylab=wx
but although everything works (and like in jupyter i can import wx just fine) still view_cube is broken but for a different error this time:
module 'wx' has no attribute 'Thread_IsMain'

Unless one of you got it working i really dont think i can be able to get this... oh well.
maybe there is conflicting Ipython version with wx?

**Comment by Ridhee** [comment]
NameError                                 Traceback (most recent call last)
<ipython-input-8-1eb96d579512> in <module>
      2 #from wx import glcanvas
      3 
----> 4 view_cube(img,[29, 19, 9])

NameError: name 'view_cube' is not defined

 I am getting its error.

I have install wx.

H
![view cube prbl](https://user-images.githubusercontent.com/84409371/118706284-d23eae00-b836-11eb-876e-b3bb000d4a29.PNG)
ow to solve this?

**Comment by tboggs** [comment]
@Ridhee You need to import the function first:

    from spectral.graphics import view_cube

Or just call `spectral.view_cube` instead.

**Comment by Ridhee** [comment]
Thank you Thomas. It worked
